"""Markdown projection — maps canonical plans into Markdown documents.

Produces a clean, human-readable Markdown representation of a study plan
with project metadata, subjects as sections, chapters as tasks with
subtask checklists, and priority indicators.
"""

from __future__ import annotations

from typing import Any

from growth.application.dtos import CanonicalPlan, ProviderSnapshot

__all__ = ["MarkdownProjection"]

_PRIORITY_LABELS: dict[str, str] = {
    "urgent": "🔴 URGENT",
    "high": "🟠 HIGH",
    "medium": "🟡 MEDIUM",
    "low": "🟢 LOW",
}


class MarkdownProjection:
    """Project a CanonicalPlan into a Markdown document snapshot."""

    @property
    def provider(self) -> str:
        return "markdown"

    def project(self, plan: CanonicalPlan) -> ProviderSnapshot:
        """Generate a Markdown document from a CanonicalPlan."""
        lines: list[str] = []
        raw: dict[str, Any] = plan.raw_payload or {}

        project_name = raw.get("project_name", plan.project_name or "Growth Plan")
        lines.append(f"# {project_name}")
        lines.append("")
        lines.append(
            f"> Generated by Growth OS · {plan.created_at.strftime('%Y-%m-%d %H:%M')}"
        )
        lines.append("")

        # Subjects, extra sections, subtask templates
        subjects = raw.get("subjects", [])
        extra_sections = raw.get("extra_sections", [])
        subtask_templates = raw.get("standard_subtasks", [])

        if subjects:
            lines.append("---")
            lines.append("")
            for subject in subjects:
                if not isinstance(subject, dict):
                    continue
                self._render_subject(lines, subject, subtask_templates)

        if extra_sections:
            lines.append("---")
            lines.append("")
            for extra in extra_sections:
                lines.append(f"## {extra}")
                lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Exported by Growth OS*")

        content = "\n".join(lines)
        return ProviderSnapshot(
            provider="markdown",
            root_id=None,
            payload={
                "project_name": project_name,
                "content": content,
                "format": "markdown",
            },
        )

    # ------------------------------------------------------------------
    # Section rendering
    # ------------------------------------------------------------------

    def _render_subject(
        self,
        lines: list[str],
        subject: dict[str, Any],
        subtask_templates: list[str],
    ) -> None:
        emoji = subject.get("emoji", "")
        name = subject.get("name", "Untitled")
        priority_raw = str(subject.get("priority", ""))
        priority_label = _PRIORITY_LABELS.get(priority_raw, "")

        heading = f"## {emoji} {name}".strip()
        if priority_label:
            heading += f"  *({priority_label})*"

        lines.append(heading)
        lines.append("")

        chapters = subject.get("chapters", [])
        if not isinstance(chapters, list):
            return

        total = len(chapters)
        for idx, chapter in enumerate(chapters):
            if not isinstance(chapter, dict):
                continue
            self._render_chapter(lines, chapter, idx, total, subtask_templates)

    # ------------------------------------------------------------------
    # Chapter / task rendering
    # ------------------------------------------------------------------

    @staticmethod
    def _render_chapter(
        lines: list[str],
        chapter: dict[str, Any],
        idx: int,
        total: int,
        subtask_templates: list[str],
    ) -> None:
        name = chapter.get("name", f"Chapter {idx + 1}")
        is_weak = bool(chapter.get("weak", False))
        tags = []

        if is_weak:
            tags.append("⚠️ weak point")
        if idx == 0:
            tags.append("▶️ next")

        suffix = f"  *({' · '.join(tags)})*" if tags else ""
        progress = f"[{idx + 1}/{total}]"
        lines.append(f"### {progress} {name}{suffix}")
        lines.append("")

        if subtask_templates:
            for st in subtask_templates:
                lines.append(f"- [ ] {st}")
            lines.append("")
