"""Unit tests for MarkdownProjection and TodoistProjection."""

from __future__ import annotations

from datetime import UTC, datetime

from growth.application.dtos import CanonicalPlan
from growth.domain.shared import DEFAULT_SPACE_ID
from growth.infrastructure.projections.markdown import MarkdownProjection
from growth.infrastructure.projections.todoist import TodoistProjection


def _plan(**payload_overrides: object) -> CanonicalPlan:
    payload: dict[str, object] = {
        "project_name": "Growth Plan",
        "subjects": [],
        "extra_sections": [],
        "standard_subtasks": [],
    }
    payload.update(payload_overrides)
    return CanonicalPlan(
        space_id=DEFAULT_SPACE_ID,
        created_at=datetime(2026, 8, 1, 12, 0, tzinfo=UTC),
        project_name="Growth Plan",
        raw_payload=payload,
    )


def _subject(**kw: object) -> dict[str, object]:
    defaults: dict[str, object] = {"name": "Math", "emoji": "📘", "chapters": []}
    defaults.update(kw)
    return defaults


def _chapter(**kw: object) -> dict[str, object]:
    defaults: dict[str, object] = {"name": "Algebra"}
    defaults.update(kw)
    return defaults


# ============================================================================
# MarkdownProjection
# ============================================================================


class TestMarkdownProjection:
    def test_provider(self) -> None:
        assert MarkdownProjection().provider == "markdown"

    def test_snapshot_shape(self) -> None:
        snap = MarkdownProjection().project(_plan())
        assert snap.provider == "markdown"
        assert snap.root_id is None
        assert set(snap.payload) == {"project_name", "content", "format"}
        assert snap.payload["format"] == "markdown"
        assert snap.payload["project_name"] == "Growth Plan"

    def test_header_and_timestamp(self) -> None:
        content = MarkdownProjection().project(_plan()).payload["content"]
        assert content.startswith("# Growth Plan\n")
        assert "> Generated by Growth OS · 2026-08-01 12:00" in content

    def test_full_plan_rendering(self) -> None:
        plan = _plan(
            subjects=[
                _subject(
                    name="Math",
                    emoji="📘",
                    priority="high",
                    chapters=[
                        _chapter(name="Algebra", weak=True),
                        _chapter(name="Geometry"),
                    ],
                )
            ],
            extra_sections=["Mistake Fix"],
            standard_subtasks=["Study", "Practice"],
        )
        content = MarkdownProjection().project(plan).payload["content"]

        assert "## 📘 Math  *(🟠 HIGH)*" in content
        assert "### [1/2] Algebra  *(⚠️ weak point · ▶️ next)*" in content
        assert "### [2/2] Geometry" in content
        assert "- [ ] Study" in content
        assert "- [ ] Practice" in content
        assert "## Mistake Fix" in content
        assert content.endswith("*Exported by Growth OS*")

    def test_priority_labels(self) -> None:
        for priority, label in [
            ("urgent", "🔴 URGENT"),
            ("high", "🟠 HIGH"),
            ("medium", "🟡 MEDIUM"),
            ("low", "🟢 LOW"),
        ]:
            plan = _plan(subjects=[_subject(name="S", priority=priority)])
            content = MarkdownProjection().project(plan).payload["content"]
            assert f"({label})" in content

    def test_unknown_priority_no_label(self) -> None:
        plan = _plan(subjects=[_subject(name="S", priority="banana")])
        content = MarkdownProjection().project(plan).payload["content"]
        assert "## 📘 S" in content
        assert "(" not in content.split("## 📘 S", 1)[1].split("\n", 1)[0]

    def test_default_project_name(self) -> None:
        plan = CanonicalPlan(
            space_id=DEFAULT_SPACE_ID,
            created_at=datetime(2026, 8, 1, 12, 0, tzinfo=UTC),
        )
        content = MarkdownProjection().project(plan).payload["content"]
        assert content.startswith("# Growth Plan\n")

    def test_raw_payload_project_name_wins(self) -> None:
        plan = _plan(project_name="Raw Name")
        content = MarkdownProjection().project(plan).payload["content"]
        assert content.startswith("# Raw Name\n")

    def test_skips_non_dict_subjects(self) -> None:
        plan = _plan(subjects=["not-a-dict", _subject(name="Real")])
        content = MarkdownProjection().project(plan).payload["content"]
        assert "## 📘 Real" in content
        assert "not-a-dict" not in content

    def test_skips_non_dict_chapters(self) -> None:
        plan = _plan(subjects=[_subject(chapters=["junk", _chapter(name="Real")])])
        content = MarkdownProjection().project(plan).payload["content"]
        assert "### [2/2] Real" in content
        assert "junk" not in content

    def test_skips_non_list_chapters(self) -> None:
        plan = _plan(subjects=[_subject(chapters="oops")])
        content = MarkdownProjection().project(plan).payload["content"]
        assert "## 📘 Math" in content
        assert "###" not in content

    def test_missing_subject_name_defaults(self) -> None:
        plan = _plan(subjects=[{"emoji": "📘"}])
        content = MarkdownProjection().project(plan).payload["content"]
        assert "## 📘 Untitled" in content

    def test_no_chapters_and_no_subtasks(self) -> None:
        plan = _plan(subjects=[_subject(name="Empty")])
        content = MarkdownProjection().project(plan).payload["content"]
        assert "## 📘 Empty" in content


# ============================================================================
# TodoistProjection
# ============================================================================


class TestTodoistProjection:
    def test_provider(self) -> None:
        assert TodoistProjection().provider == "todoist"

    def test_snapshot_shape(self) -> None:
        snap = TodoistProjection().project(_plan())
        assert snap.provider == "todoist"
        assert snap.root_id is None
        assert set(snap.payload) == {"project_name", "sections", "items"}
        assert snap.payload["project_name"] == "Growth Plan"

    def test_project_name_from_plan(self) -> None:
        plan = CanonicalPlan(
            space_id=DEFAULT_SPACE_ID,
            created_at=datetime(2026, 8, 1, tzinfo=UTC),
            project_name="My Todoist Plan",
            raw_payload={"subjects": []},
        )
        snap = TodoistProjection().project(plan)
        assert snap.payload["project_name"] == "My Todoist Plan"

    def test_default_project_name(self) -> None:
        plan = CanonicalPlan(
            space_id=DEFAULT_SPACE_ID,
            created_at=datetime(2026, 8, 1, tzinfo=UTC),
        )
        snap = TodoistProjection().project(plan)
        assert snap.payload["project_name"] == "Growth Plan"
        assert snap.payload["sections"] == []
        assert snap.payload["items"] == []

    def test_sections_from_subjects_and_extra(self) -> None:
        plan = _plan(
            subjects=[
                _subject(name="Math", emoji="📘"),
                _subject(name="Physics", emoji=""),
            ],
            extra_sections=["Mistake Fix"],
        )
        snap = TodoistProjection().project(plan)
        assert snap.payload["sections"] == [
            {"name": "📘 Math"},
            {"name": "Physics"},
            {"name": "Mistake Fix"},
        ]

    def test_sections_skip_non_dict_subjects(self) -> None:
        plan = _plan(subjects=["junk", _subject(name="Real")])
        snap = TodoistProjection().project(plan)
        assert snap.payload["sections"] == [{"name": "📘 Real"}]

    def test_priority_mapping(self) -> None:
        cases = [("urgent", 4), ("high", 3), ("medium", 2), ("low", 1), ("banana", 1)]
        for priority, expected in cases:
            plan = _plan(
                subjects=[
                    _subject(name="S", priority=priority, chapters=[_chapter(name="C")])
                ]
            )
            snap = TodoistProjection().project(plan)
            assert snap.payload["items"][0]["priority"] == expected

    def test_weak_chapter_gets_max_priority(self) -> None:
        plan = _plan(
            subjects=[
                _subject(
                    name="Math",
                    priority="low",
                    chapters=[_chapter(name="Weak one", weak=True)],
                )
            ]
        )
        snap = TodoistProjection().project(plan)
        assert snap.payload["items"][0]["priority"] == 4

    def test_items_carry_subtasks(self) -> None:
        plan = _plan(
            subjects=[_subject(chapters=[_chapter(name="Algebra")])],
            standard_subtasks=["Study", "Practice"],
        )
        snap = TodoistProjection().project(plan)
        item = snap.payload["items"][0]
        assert item["content"] == "Algebra"
        assert item["section"] == "Math"
        assert item["subtasks"] == ["Study", "Practice"]

    def test_items_skip_non_dict_chapters(self) -> None:
        plan = _plan(subjects=[_subject(chapters=["junk", _chapter(name="Real")])])
        snap = TodoistProjection().project(plan)
        assert [i["content"] for i in snap.payload["items"]] == ["Real"]

    def test_items_skip_non_list_chapters(self) -> None:
        plan = _plan(subjects=[_subject(chapters="oops")])
        snap = TodoistProjection().project(plan)
        assert snap.payload["items"] == []

    def test_subtasks_not_list_ignored(self) -> None:
        plan = _plan(
            subjects=[_subject(chapters=[_chapter(name="Algebra")])],
            standard_subtasks="not-a-list",
        )
        snap = TodoistProjection().project(plan)
        assert snap.payload["items"][0]["subtasks"] == []
